CREATE TABLE IF NOT EXISTS regions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_name VARCHAR(255) NOT NULL UNIQUE,
    emergency_phone VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    icon_name VARCHAR(255),
    accent_color VARCHAR(255),
    display_order INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS memo (
    id UUID PRIMARY KEY,
    category_id BIGINT,
    region_id BIGINT,
    title VARCHAR(255) NOT NULL,
    short_description VARCHAR(500) NOT NULL,
    icon_name VARCHAR(255),
    accent_color VARCHAR(255),
    content TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    is_critical BOOLEAN NOT NULL DEFAULT FALSE,
    image_url VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_memo_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_memo_region FOREIGN KEY (region_id) REFERENCES regions (id)
);

CREATE TABLE IF NOT EXISTS memo_steps (
    memo_id UUID NOT NULL,
    step TEXT NOT NULL,
    CONSTRAINT fk_memo_steps_memo FOREIGN KEY (memo_id) REFERENCES memo (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sos_events (
    id UUID PRIMARY KEY,
    target_type VARCHAR(64) NOT NULL,
    region_id BIGINT,
    contact_phone VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    accuracy_meters INTEGER,
    address VARCHAR(500),
    status VARCHAR(64) NOT NULL,
    sms_delivery_status VARCHAR(64) NOT NULL,
    sms_provider_message VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_sos_events_region FOREIGN KEY (region_id) REFERENCES regions (id)
);

CREATE TABLE IF NOT EXISTS alarm (
    id UUID PRIMARY KEY,
    region_id BIGINT NOT NULL,
    text TEXT NOT NULL,
    CONSTRAINT fk_alarm_region FOREIGN KEY (region_id) REFERENCES regions (id)
);

CREATE INDEX IF NOT EXISTS idx_categories_display_order ON categories (display_order);
CREATE INDEX IF NOT EXISTS idx_memo_region_id ON memo (region_id);
CREATE INDEX IF NOT EXISTS idx_memo_category_id ON memo (category_id);
CREATE INDEX IF NOT EXISTS idx_memo_is_active ON memo (is_active);
CREATE INDEX IF NOT EXISTS idx_memo_is_critical ON memo (is_critical);
CREATE INDEX IF NOT EXISTS idx_alarm_region_id ON alarm (region_id);
CREATE INDEX IF NOT EXISTS idx_sos_events_region_id ON sos_events (region_id);
